container_port: 8080
service_port: 80

replicas: 1

container_resource_limits:
  cpu: 1
  memory: 1Gi
container_resource_requests:
  cpu: 50m
  memory: 256Mi

env_vars:
  LOG_LEVEL: info
  DB_HOST: {{cookiecutter.db_host}}
  DB_NAME: {{cookiecutter.db_name}}
  DB_USERNAME: {{cookiecutter.db_username}}
  DB_SCHEMA: {{cookiecutter.db_schema}}

secrets:
  DB_PASSWORD: {{cookiecutter.db_password_planton_cloud_secret_id}}
